# Generated by Django 5.1.4 on 2024-12-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vraag', models.TextField(max_length=200)),
                ('antwoord', models.TextField(blank=True, max_length=100)),
                ('gemaakt', models.DateTimeField(auto_now_add=True)),
                ('geupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
